### ISSUE TITLE
Recursive serialization

### ISSUE THREAD

**Issue by gregorybchris** [tekknolagi/scrapscript#47]
For example,

```
fac =
| 0 -> 1
| n -> n * fac (n - 1)
```

won't serialize because it results in a closure that references itself.

**Comment by tekknolagi** [comment]
We can probably take a leaf out of Python marshal's book and use refs + ref indices

**Comment by tekknolagi** [comment]
CBOR with value sharing: http://cbor.schmorp.de/value-sharing
